require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'BestBets' do
  use_unimodules!(exclude: ['expo-splash-screen'])
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'BestBetsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'BestBets-tvOS' do
  # Pods for BestBets-tvOS

  target 'BestBets-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
